### ISSUE TITLE
target location not configurable

### ISSUE THREAD

**Issue by baszoetekouw** [SURFnet/Service-provider-registration#64]
The new APC cache clearing target requires the deployement location to be known.  Currently, it is defined in config.yaml:
```yml
accelerator_cache:
    host: https://support.surfconext.nl/intake/
    web_dir: %kernel.root_dir%/../web
```
This host name/url should be configurable in parameter.yml, instead.
